In [114]:
# TensorFlow的一些简单接口

In [ ]:
import numpy as np
import pandas as pd
import time
import tensorflow as tf

In [115]:
# constant是常量张量
c = tf.constant([[1., 2., 3.], [4., 5., 6.]])
# 高版本能够直接获取值是因为execution默认打开的
print(c)
print(c[:,1:])
print(c[...,1])
# c.assign(1) # 对常量不能再次assign进行设置
print(type(c.numpy())) # 转为ndarray

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[2. 3.]
 [5. 6.]], shape=(2, 2), dtype=float32)
tf.Tensor([2. 5.], shape=(2,), dtype=float32)
<class 'numpy.ndarray'>


In [116]:
nd=c.numpy()
t1=tf.constant(nd) # 把ndarray变为张量
print(t1)
print(type(t1))

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [117]:
# ops 使用tf本身的math接口对Tensor进行计算
print(c)
print(c+10)
print(tf.square(c))
print(c)
print(tf.transpose(c))
# 矩阵乘以自己的转置矩阵
# @是矩阵乘法  *是对应位置元素相乘运算
print(c@tf.transpose(c))
C = tf.constant([[1., 2., 3.], [4., 5., 6.],[7, 8, 9]])
print(C*tf.transpose(C))
print(c)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[11. 12. 13.]
 [14. 15. 16.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 4.]
 [2. 5.]
 [3. 6.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[14. 32.]
 [32. 77.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 1.  8. 21.]
 [ 8. 25. 48.]
 [21. 48. 81.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


In [118]:
print(tf.sqrt(c))
print(tf.math.sqrt(c))
print(tf.math.log(c))

tf.Tensor(
[[1.        1.4142135 1.7320508]
 [2.        2.236068  2.4494898]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1.        1.4142135 1.7320508]
 [2.        2.236068  2.4494898]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[0.        0.6931472 1.0986123]
 [1.3862944 1.609438  1.7917595]], shape=(2, 3), dtype=float32)


In [119]:
# numpy conversion
print(c.numpy()) # 可以直接通过numpy取出来
print(c.numpy().tolist())
print(type(c.numpy())) # <class 'numpy.ndarray'>
print(np.square(c))
print(type(np.square(c))) # <class 'numpy.ndarray'>
np_t = np.array([[1., 2., 3.], [4., 5., 6.]])
print(tf.constant(np_t))
print(type(tf.constant(np_t)))

[[1. 2. 3.]
 [4. 5. 6.]]
[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]
<class 'numpy.ndarray'>
[[ 1.  4.  9.]
 [16. 25. 36.]]
<class 'numpy.ndarray'>
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float64)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [120]:
# 标量 scalar
s=tf.constant(3.14159265)
print(s)
print(s.numpy())
print(s.shape)

tf.Tensor(3.1415927, shape=(), dtype=float32)
3.1415927
()


In [121]:
# strings
t_str=tf.constant('cafe')
print(t_str)
print(tf.strings.length(t_str))
print(tf.strings.length(t_str,unit='UTF8_CHAR'))
print(tf.strings.unicode_decode(t_str,'UTF8'))


tf.Tensor(b'cafe', shape=(), dtype=string)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([ 99  97 102 101], shape=(4,), dtype=int32)


In [122]:
# string array
t_str_arr = tf.constant(["cafe", "coffee", "咖啡"])
# 自动求出数组中每一个字符的长度
print(tf.strings.length(t_str_arr)) # 实际字节存储的长度
print(tf.strings.length(t_str_arr,unit='UTF8_CHAR'))
print(tf.strings.length(t_str_arr,unit='BYTE'))
# https://tool.chinaz.com/tools/unicode.aspx  汉字转的是unicode编码
r=tf.strings.unicode_decode(t_str_arr,'UTF8')
print(r)

tf.Tensor([4 6 6], shape=(3,), dtype=int32)
tf.Tensor([4 6 2], shape=(3,), dtype=int32)
tf.Tensor([4 6 6], shape=(3,), dtype=int32)
<tf.RaggedTensor [[99, 97, 102, 101], [99, 111, 102, 102, 101, 101], [21654, 21857]]>


In [123]:
# TensorFlow2.0新增 RaggedTensor 是指形状分布不固定的（行元素个数不相等）
# ragged tensor
r = tf.ragged.constant([[11, 12], [21, 22, 23], [0], [41]])
print(r)
print(r.shape)
print(r[1])
print(type(r[2])) # <class 'tensorflow.python.framework.ops.EagerTensor'>
print(r[2:3])
print(type(r[2:3])) # <class 'tensorflow.python.ops.ragged.ragged_tensor.RaggedTensor'>
print('-'*50)
print(r[1,1])
# print(r[:,0]) # 不能取列索引

<tf.RaggedTensor [[11, 12], [21, 22, 23], [0], [41]]>
(4, None)
tf.Tensor([21 22 23], shape=(3,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
<tf.RaggedTensor [[0]]>
<class 'tensorflow.python.ops.ragged.ragged_tensor.RaggedTensor'>
--------------------------------------------------
tf.Tensor(22, shape=(), dtype=int32)


In [124]:
# ops on ragged tensor
r2 = tf.ragged.constant([[51, 52],[], [], [71]])
print(tf.concat([r,r2],axis=0))
print(tf.concat([r,r2],axis=1)) # 注意行数不相等不可以拼接

<tf.RaggedTensor [[11, 12], [21, 22, 23], [0], [41], [51, 52], [], [], [71]]>
<tf.RaggedTensor [[11, 12, 51, 52], [21, 22, 23], [0], [41, 71]]>


In [125]:
print(r)
# 各种深度学习模型必须输入一个tensor
print(r.to_tensor()) # 空位往后补0

<tf.RaggedTensor [[11, 12], [21, 22, 23], [0], [41]]>
tf.Tensor(
[[11 12  0]
 [21 22 23]
 [ 0  0  0]
 [41  0  0]], shape=(4, 3), dtype=int32)


In [126]:
# sparse tensor 可以往前面补零,sparse tensor从第一行依次往下填位置
# sparese tensor存储节省内存空间，磁盘空间
s=tf.SparseTensor(indices=[[0, 1], [1, 0], [2, 3],[3, 2]], # 位置
                 values=[1, 2, 3., 5], # 值
                 dense_shape=[4, 4]) # 维数
print(s)
tt=tf.sparse.to_dense(s)
print(tt)

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]
 [3 2]], shape=(4, 2), dtype=int64), values=tf.Tensor([1. 2. 3. 5.], shape=(4,), dtype=float32), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))
tf.Tensor(
[[0. 1. 0. 0.]
 [2. 0. 0. 0.]
 [0. 0. 0. 3.]
 [0. 0. 5. 0.]], shape=(4, 4), dtype=float32)


In [127]:
s2=s*2.
print(s2)
# SparseTensor不支持加法
try:
    s3=s+s2
except TypeError as ex:
    print(ex)
t = tf.constant([[10., 20.],
                  [30., 40.],
                  [50., 60.],
                  [70., 80.]])
# SparseTensor和Tensor相乘
print(tf.sparse.to_dense(s)@t)
print(tf.sparse.sparse_dense_matmul(s,t))

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]
 [3 2]], shape=(4, 2), dtype=int64), values=tf.Tensor([ 2.  4.  6. 10.], shape=(4,), dtype=float32), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))
unsupported operand type(s) for +: 'SparseTensor' and 'SparseTensor'
tf.Tensor(
[[ 30.  40.]
 [ 20.  40.]
 [210. 240.]
 [250. 300.]], shape=(4, 2), dtype=float32)
tf.Tensor(
[[ 30.  40.]
 [ 20.  40.]
 [210. 240.]
 [250. 300.]], shape=(4, 2), dtype=float32)


In [128]:
s = tf.SparseTensor(indices = [[0, 2], [2, 3], [1, 2], [0, 1]],
                    values = [1., 2., 3., 4],
                    dense_shape = [3, 4])
# print(tf.sparse.to_dense(s)) # SparseTensor的indices无序时，不能转为tensor
print(s)
ss=tf.sparse.reorder(s)
print(ss)
print(tf.sparse.to_dense(ss))


SparseTensor(indices=tf.Tensor(
[[0 2]
 [2 3]
 [1 2]
 [0 1]], shape=(4, 2), dtype=int64), values=tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
SparseTensor(indices=tf.Tensor(
[[0 1]
 [0 2]
 [1 2]
 [2 3]], shape=(4, 2), dtype=int64), values=tf.Tensor([4. 1. 3. 2.], shape=(4,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[0. 4. 1. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 2.]], shape=(3, 4), dtype=float32)


In [129]:
# Variables
v = tf.Variable([[1., 2., 3.], [4., 5.,6.]])
print(v)
print(type(v)) # <class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
print(v.value())
print(v.numpy())

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
[[1. 2. 3.]
 [4. 5. 6.]]


In [130]:
# 修改变量时要用assign，会在原地址空间改变tensor内某个值
print(id(v))
v.assign(v*2)
print(v.numpy())
print('-'*50)
v[0,1].assign(66)
print(v.numpy())
print(id(v))
print('-'*50)
v[1].assign([7., 8., 9.])
print(v.numpy())
print(id(v))
print(type(v))

1445085386592
[[ 2.  4.  6.]
 [ 8. 10. 12.]]
--------------------------------------------------
[[ 2. 66.  6.]
 [ 8. 10. 12.]]
1445085386592
--------------------------------------------------
[[ 2. 66.  6.]
 [ 7.  8.  9.]]
1445085386592
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>


In [131]:
try:
    v[1]=[7,8,9.]
except TypeError as ex:
    print(ex)

'ResourceVariable' object does not support item assignment


In [132]:

v=2*v
print(v)
print(id(v))
print(type(v)) # <class 'tensorflow.python.framework.ops.EagerTensor'>

tf.Tensor(
[[  4. 132.  12.]
 [ 14.  16.  18.]], shape=(2, 3), dtype=float32)
1445007212608
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [133]:
x = tf.constant([[1., 1.], [2., 2.]])
# 计算张量tensor沿着指定的数轴（tensor的某一维度）上的平均值
print(tf.reduce_mean(x, axis=0))
print(tf.reduce_mean(x, axis=1))

tf.Tensor([1.5 1.5], shape=(2,), dtype=float32)
tf.Tensor([1. 2.], shape=(2,), dtype=float32)
