In [81]:
# 数据集

In [ ]:
import tensorflow as tf
import numpy as np
import sklearn
import pandas as pd

In [82]:
# 内存中构建dataset并初始化，返回的类似于一个迭代器
print(np.arange(10))
dataset = tf.data.Dataset.from_tensor_slices(np.arange(10))
print(dataset) # TensorSliceDataset shape=()
print(list(dataset.as_numpy_iterator()))
print('-' * 50)
print(tf.data.Dataset.from_tensors(np.arange(10))) # TensorDataset shape=(10,)
print(list(tf.data.Dataset.from_tensors(np.arange(10)).as_numpy_iterator()))

[0 1 2 3 4 5 6 7 8 9]
<TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
--------------------------------------------------
<TensorDataset element_spec=TensorSpec(shape=(10,), dtype=tf.int32, name=None)>
[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])]


In [83]:
# 可以遍历，每一个都是tensor
for item in dataset:
    print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


In [84]:
dataset1 = dataset.repeat(3)  #重复次数(无参数无限重复) 比如读到结尾返回开头重新读3次
print(dataset1) # RepeatDataset
for item in dataset1:
    print(item)

<RepeatDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), 

In [85]:
# repeat epoch 遍历一次数据集
# get batch 取一部分数据集
dataset = dataset.repeat(3).batch(7)  # 每7个tensor组合成一个新的tensor
print(dataset) # BatchDataset shape=(None,)
i = 0
for item in dataset:
    i = i + 1
    print(item) #s hape=(7,)
print(i)
print('-' * 50)
for i in dataset:
    print(i)

<BatchDataset element_spec=TensorSpec(shape=(None,), dtype=tf.int32, name=None)>
tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
tf.Tensor([8 9], shape=(2,), dtype=int32)
5
--------------------------------------------------
tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
tf.Tensor([8 9], shape=(2,), dtype=int32)


In [86]:
# 从原始数据中取出cycle_length个元素，对这些元素应用map_func，得到cycle_length个dataset对象，
# 轮流重复从每个dataset对象取出block_length个数据，当某个dataset的对象取尽时，再次从原始数据中取出cycle_length个元素，以此类推
dataset2 = dataset.interleave(lambda v: tf.data.Dataset.from_tensor_slices(v), # map_fn，第一参数是回调函数
                              cycle_length=3, # cycle_length,每一个cycle提取的个数
                              block_length=2)
print(dataset2) # InterleaveDataset
print('-' * 50)
i = 0
for item in dataset2:
    i = i + 1
    print(item)
print(i)

<InterleaveDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>
--------------------------------------------------
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.T

In [87]:
a = tf.data.Dataset.range(1, 6)
b = a.repeat(6)
for i in b:
    print(i)
print('-' * 50)
a1 = a.interleave(lambda x: tf.data.Dataset.from_tensors(x),
                  cycle_length=3, block_length=4)
for i in a1:
    print(i)

tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype

In [88]:
# 各种格式数据转换为dataset
# 元组
x = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array(['cat', 'dog', 'fox'])
dataset3 = tf.data.Dataset.from_tensor_slices((x, y))
print(dataset3)
for item_x, item_y in dataset3:
    print(item_x, item_y)

<TensorSliceDataset element_spec=(TensorSpec(shape=(2,), dtype=tf.int32, name=None), TensorSpec(shape=(), dtype=tf.string, name=None))>
tf.Tensor([1 2], shape=(2,), dtype=int32) tf.Tensor(b'cat', shape=(), dtype=string)
tf.Tensor([3 4], shape=(2,), dtype=int32) tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor([5 6], shape=(2,), dtype=int32) tf.Tensor(b'fox', shape=(), dtype=string)


In [89]:
# 字典
dataset4 = tf.data.Dataset.from_tensor_slices({"feature1": x,
                                               "label": y})
print(dataset4)
for item in dataset4:
    print(item['feature1'], item['label'])

<TensorSliceDataset element_spec={'feature1': TensorSpec(shape=(2,), dtype=tf.int32, name=None), 'label': TensorSpec(shape=(), dtype=tf.string, name=None)}>
tf.Tensor([1 2], shape=(2,), dtype=int32) tf.Tensor(b'cat', shape=(), dtype=string)
tf.Tensor([3 4], shape=(2,), dtype=int32) tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor([5 6], shape=(2,), dtype=int32) tf.Tensor(b'fox', shape=(), dtype=string)


In [90]:
a = tf.data.Dataset.range(1, 6)  # [ 1, 2, 3, 4, 5 ]
print(a) # RangeDataset
print(list(a.as_numpy_iterator()))
print('-' * 50)
a1=tf.data.Dataset.from_tensors(a).repeat(6)
for i in a1:
    print(list(i.as_numpy_iterator()))
    for j in i:
        print(j)
print('-' * 50)
# NOTE: New lines indicate "block" boundaries.
b = a.interleave(lambda x: tf.data.Dataset.from_tensors(x).repeat(6),
                 cycle_length=2, block_length=4)    # ==> [1, 1, 1, 1,
                                                    #      2, 2, 2, 2,
                                                    #      1, 1,
                                                    #      2, 2,
                                                    #      3, 3, 3, 3,
                                                    #      4, 4, 4, 4,
                                                    #      3, 3,
                                                    #      4, 4,
                                                    #      5, 5, 5, 5,
                                                    #      5, 5]
print(b)
for item in b:
     print(item)
   



<RangeDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
[1, 2, 3, 4, 5]
--------------------------------------------------
[1, 2, 3, 4, 5]
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
[1, 2, 3, 4, 5]
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
[1, 2, 3, 4, 5]
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
[1, 2, 3, 4, 5]
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
[1, 2, 3, 4, 5]
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=()